{% set version="1.0.2j" %}

package:
  name: openssl
  version: {{ version }}

source:
  fn: openssl-{{ version }}.tar.gz
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: e7aff292be21c259c6af26469c7a9b3ba26e9abaaffd325e3dccc9785256c431

build:
  number: 0
  no_link: lib/libcrypto.so.1.0.0        # [linux]
  no_link: lib/libcrypto.1.0.0.dylib     # [osx]
  detect_binary_files_with_prefix: True  # [unix]
  has_prefix_files:                      # [unix]
    - bin/c_rehash                       # [unix]
    - include/openssl/opensslconf.h      # [unix]
    - lib/pkgconfig/libcrypto.pc         # [unix]
    - lib/pkgconfig/libssl.pc            # [unix]
    - lib/pkgconfig/openssl.pc           # [unix]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]


requirements:
  build:
    # for feature activation
    - python             # [win]
    # required for win32: https://wiki.openssl.org/index.php/Compilation_and_Installation#Windows
    - nasm               # [win32]
    - perl
  run:
    - ca-certificates

test:
  requires:
    - python   2.7.*   # [py27]
    - python   3.4.*   # [py34]
    - python   3.5.*   # [py35]
  imports:
    - ssl
  commands:
    - copy NUL checksum.txt        # [win]
    - touch checksum.txt           # [unix]
    - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license: Apache-style (http://www.openssl.org/source/license.html)
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
