build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider:
  # failing test on aarch in emulation, see #84
  linux_aarch64: travis
  linux_ppc64le: default
test_on_native_only: true
conda_build:
  pkg_format: '2'
