bot:
  abi_migration_branches:
  - 1.1.1
  - 3.0.x
conda_forge_output_validation: true
provider:
  # failing test on aarch in emulation, see #84
  linux_aarch64: travis
  linux_ppc64le: default
test_on_native_only: true
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
